Feature/1/signup
khu-open-source/movie-client pull request #2
Opened 2022-11-23 09:21 UTC by yerinjo

## Description
- 회원가입기능: 이메일, 아이디, 비밀번호, 비밀번호 확인 입력
- 로그인: 아이디, 비밀번호 입력

## Related Issue
- 회원가입기능과 로그인을 보강하였고 버튼 추가 완료

## Motivation and Context
- 정적으로 각각 단일 페이지 제작.

## Screenshots
<img width="1470" alt="스크린샷 2022-11-23 오후 6 17 42" src="https://user-images.githubusercontent.com/114723339/203509813-232caf43-e896-4e51-86c4-51a36b35eed4.png">

2022-11-23 16:38 UTC, L2HYUNN requested changes
`signin.js` 같은 경우는 연습용으로 해보신걸까요?

`react`의 경우 작동 방식이 다르기 때문에 해당 코드를 사용할 수 없습니다 :(

2022-11-23 16:38 UTC, L2HYUNN commented on src/App.js
> +  </div>
react에서 기본으로 제공하는 디자인들 전부 삭제하셔도 돼요!

2022-11-23 16:38 UTC, L2HYUNN commented on src/pages/Login.jsx
> +    </div>
반복되는 부분은 따로 컴포넌트화 하는게 좋습니다

또한 `nav`, `ul`, `li` 같은 tag를 이용하면 semantic하게 작성하면 더 좋을 거 같아요.
```suggestion
    <ul className="form-header">
      <li className="show-signup">Sign Up</li>
      <li className="show-signin">Sign In</li>
      <li className="show-reset">Reset</li>
    </ul>
```

2022-11-23 16:38 UTC, L2HYUNN commented on src/pages/Login.jsx
> +      </div>
`input` tag를 이용한다는 것은 무언가를 입력받는 것이고 그렇다면 나중에 제출하기 위해서 `form` 태그가 필요할 거 같네요 

그리고 Login에는 `confirm password`는 필요 없을 거 같아요!

2022-11-23 16:38 UTC, L2HYUNN commented on src/pages/login.css
> +  .form {
전부 `indent`가 들어가있네요! 특별한 이유 없이는 하지 않는게 좋습니다

2022-11-23 16:38 UTC, L2HYUNN commented on src/pages/login.css
> +  .form .form-header {
`form`안에 `form-header`에 적용하기 위함일까요? 그렇다면 `.form-header`만 이용해도 가능할 거 같아요

`selector`가 복잡한 것은 좋지 않습니다! 최대한 간단하게 신경써주시면 더 좋은 코드가 될 거 같아요 :)

2022-11-23 16:38 UTC, L2HYUNN commented on src/pages/login.css
> +  .form .form-elements .form-element {
`element`는 안 붙여도 괜찮을 거 같아요!

2022-11-27 07:47 UTC, yoonsaeng approved these changes
LGTM

2022-11-27 07:49 UTC, L2HYUNN approved these changes
LGTM

2022-11-27 07:49 UTC, merged