Feature/2/header
khu-open-source/movie-client pull request #4
Opened 2022-11-23 10:35 UTC by yoonsaeng

## Description
- 상단 메뉴바

## Related Issue
- 필요적인 부분 생성
- 검색 기능 로직 더 구현 필요
- css 디테일 필요

## Motivation and Context
- 상단 메뉴바 고정 or 이동 고민

## Screenshots

2022-11-23 14:49 UTC, yerinjo commented
수정이 필요합니다.

2022-11-23 16:17 UTC, L2HYUNN requested changes

2022-11-23 16:17 UTC, L2HYUNN commented on src/components/Header/Header.js
> +      </option>
이 부분 왜 option tag로 사용되어 있을까요? nav > ul > li > button 정도가 적당해보여요

2022-11-23 16:17 UTC, L2HYUNN commented on src/components/Header/Header.js
> +        </li>
이부분은 하드코딩하기 보다 list, map 함수를 이용하는게 좋아 보여요

```javascript
const categoryList = ['Popular', 'Animation', 'Romance', 'Science Fiction', 'Action'];
```

Header 컴포넌트 밖에 위와 같이 list로 정의합니다.

```suggestion
        {categoryList.map((list) => (
          <li key={list}>
            <Link to={list.toLowerCase()}>{list}</Link>
          </li>
        ))}
```

2022-11-23 16:17 UTC, L2HYUNN commented on src/components/Header/Header.js
> +import { Link } from 'react-router-dom';
이런거 올리실 때 `package.json` 신경써주셔야해요
현재 ```package.json```에 `react-router-dom`이 명시되어 있지 않기 때문에 에러가 발생할 수 있습니다.

또한 ```react-router-dom```을 사용하기 위해서는 ```index.js```에 설정을 진행해주어야 하는데 해당 부분이 빠져있어서 리뷰하기 쉽지 않네요.

```npm start``` 했을 때 바로 페이지 확인 가능한 형태로 작업해주시면 좋을 거 같습니다 :)

2022-11-23 16:17 UTC, L2HYUNN commented on src/components/Header/Header.css
> +a{text-decoration:none;color:#fff;font-size:15px}
이 부분은 왜 이렇게 정리되어있을까요? 

아래와 같은 형태가 리뷰하기 좋습니다 ~! 
일관된 형태로 가져가는 것도 중요해요!

2022-11-27 07:50 UTC, L2HYUNN approved these changes
LGTM

2022-11-27 07:51 UTC, merged